{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.pvName | default (include "helm-base.fullname" .) }}
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.persistence.nfs.server }}
    path: {{ .Values.persistence.nfs.path }}   # full export, no subPath
  mountOptions:
    {{- range .Values.persistence.nfs.mountOptions | default (list "vers=4") }}
    - {{ . }}
    {{- end }}
{{- end }}
