{{- if .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-base.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.configmaps }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
