{{- if .Values.sealed }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "helm-base.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.sealed }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}
